name:                haskell-training
version:             0.1.0.0
github:              "githubuser/haskell-training"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-training#readme>

dependencies:
- base >= 4.7 && < 5
- uuid >= 1.3.13
- aeson >= 1.2.4.0
- text >= 1.2.3

library:
  source-dirs: src
  ghc-options:
  - -Wall

tests:
  haskell-training-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-training
    - QuickCheck
    - hspec
